/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.graalvm.buildtools.native") version "0.9.27"
}

repositories {
    mavenCentral()
}

dependencies {
    // https://mvnrepository.com/artifact/com.google.zetasketch/zetasketch
    implementation("com.google.zetasketch:zetasketch:0.1.0")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

graalvmNative {
    binaries {
        named("main") {
            buildArgs.add("--initialize-at-build-time=com.google.zetasketch,com.google.protos.zetasketch")
        }
    }
}

application {
    mainClass.set("graalvm.zetasketch.App")
}
